const MoviesInfo = [
  {
    id: 1,
    img: "https://www.letelegramme.fr/images/2017/05/07/marine-vacth-est-l-actrice-principale-du-dernier-film-de_3414316.jpg",
    name: "L'amant double",
    release_dates: "2017",
    running_time: "109 minutes",
    language: "Deutsch, Französisch",
  },
  {
    id: 2,
    img: "https://m.media-amazon.com/images/I/91G2my8TUjL._SL1500_.jpg",
    name: "Now You See Me ",
    release_dates: "2013",
    running_time: "115 minutes",
    language: "English",
  },
  {
    id: 3,
    img: "https://www.tvguide.com/a/img/catalog/provider/1/2/1-11528019650.jpg",
    name: "	The Back-Up Plan",
    release_dates: "2010",
    running_time: "106 minutes",
    language: "English",
  },
  {
    id: 4,
    img: "https://upload.wikimedia.org/wikipedia/en/5/50/RatatouillePoster.jpg",
    name: "Ratatouille",
    release_dates: "2007",
    running_time: "111 minutes",
    language: "English",
  },
  {
    id: 5,
    img: "https://upload.wikimedia.org/wikipedia/en/thumb/a/a7/Identity_Thief_Poster.jpg/220px-Identity_Thief_Poster.jpg",
    name: "Identity Thief",
    release_dates: "2013",
    running_time: "111 minutes",
    language: "English",
  },
  {
    id: 6,
    img: "https://upload.wikimedia.org/wikipedia/en/4/42/Change_up_poster.jpg",
    name: "The Change-Up",
    release_dates: "2011",
    running_time: "112 minutes",
    language: "English",
  },
  {
    id: 7,
    img: "https://upload.wikimedia.org/wikipedia/en/1/1c/Free_Guy_2021_Poster.jpg",
    name: "Free Guy",
    release_dates: "2021",
    running_time: "115 minutes",
    language: "English",
  },

  {
    id: 8,
    img: "https://upload.wikimedia.org/wikipedia/en/thumb/b/b9/Hangoverposter09.jpg/220px-Hangoverposter09.jpg",
    name: "The Hangover",
    release_dates: "2009",
    running_time: "100 minutes",
    language: "English",
  },
  {
    id: 9,
    img: "https://upload.wikimedia.org/wikipedia/en/thumb/2/21/Burnt_Poster_Updated.jpg/220px-Burnt_Poster_Updated.jpg",
    name: "Burnt ",
    release_dates: "2015",
    running_time: "101 minutes",
    language: "English, French",
  },
  {
    id: 10,
    img: "https://upload.wikimedia.org/wikipedia/en/7/75/Demain_tout_commence.jpg",
    name: "Two Is a Family",
    release_dates: "2016",
    running_time: "135 minutes",
    language: "	French",
  },
  {
    id: 11,
    img: "https://upload.wikimedia.org/wikipedia/en/b/b2/Keeping_Up_with_the_Joneses_%28film%29.png",
    name: "Keeping Up with the Joneses",
    release_dates: "2016",
    running_time: "105 minutes",
    language: "English",
  },
  {
    id: 12,
    img: "https://upload.wikimedia.org/wikipedia/en/8/8a/The_Avengers_%282012_film%29_poster.jpg",
    name: "Marvel's The Avengers",
    release_dates: "2012",
    running_time: "143 minutes",
    language: "English",
  },
];
export default MoviesInfo;
